---
apiVersion: v1
kind: Namespace
metadata:
  name: amp-uat
  labels:
    istio-injection: disabled
    kubesphere.io/workspace: system-workspace
    kubesphere.io/managed: "true"
  annotations:
    kubesphere.io/description: "AMP UAT namespace with Istio sidecar injection disabled"
    kubesphere.io/creator: system